# Selin Jessa
# April 2020
#
# This file contains custom functions I've written to generate the same
# plots as in functions_fda.R, using ggplot2 so they are more customizable,
# making heavy use of the plotting methods in the funData package

library(ggplot2)
library(fda)
library(funData)
library(tidyr)
library(dplyr)
library(cowplot)


brain_region_labels <- c("A1C" = "Primary auditory cortex",
                         "AMY" = "Amygdala",
                         "CBC_URL" = "Upper rhombic lip /\n cerebellar cortex",
                         "DFC" = "Dorsolateral prefrontal cortex",
                         "HIP" = "Hippocampus",
                         "IPC" = "Posterior inferior parietal cortex",
                         "ITC" = "Inferior temporal cortex",
                         "M1C_S1C" = "Primary motor &\n somatosensory cortex",
                         "MD_DTH" = "Thalamus",
                         "MFC" = "Medial prefrontal cortex",
                         "OFC" = "Orbital prefrontal cortex",
                         "S1C_PCx" = "Parietal cerebral wall /\nprimariy somatosensory \ncortex",
                         "STC" = "Superior temporal cortex",
                         "STR_MGE" = "Medial ganglionic eminence /\n striatum",
                         "V1C_Ocx" = "Occipital cerebral wall /\n primary visual \ncortex",
                         "VFC" = "Ventrolateral prefrontal \ncortex")

region_labeller <- function(variable, value) {
  return(brain_region_labels[value])
}


#' Plot FDA curves or derivatives with ggplot2
#'
#' @param fda_output List, as generated by createFDAcurves
#' @param plot Character, one of "fitted" (to plot the smoothed data),
#' or "derivatives" (to plot the derivatives of the curves)
#' @param palette Palette from RColorBrewer to interpolate, or named character vector
#' with names corresponding to the elements of fda_output$fdNames$region
#' @param ncol_legend Numeric, number of columns with which to display the legend
#'
#' @return
plotFDAcurves <- function(fda_output, ncol_legend = 1, ...) {
  
  # The funData package has plotting methods for fda objects
  # using ggplot2
  require(funData)
  require(RColorBrewer)
  
  fdobj <- fda_output$lst_GE_FD[[1]]
  
  # We need to provide the values at which the fda curves will be approximated,
  # so I'll follow the defaults used in the fda package:
  # https://github.com/cran/fda/blob/master/R/plot.fd.R#L18
  basisobj <- fdobj$basis
  rangex   <- basisobj$rangeval
  nbasis   <- dim(fdobj$coefs)[1]
  nx       <- max(c(501,10*nbasis + 1))
  y        <- seq(rangex[1], rangex[2], len = round(nx))
  
  fundataobj <- fd2funData(fdobj, y)
  
  # Plot w/ ggplot2 ----
  palette <- palette_brainspan
  
  p1 <- autoplot(fundataobj) +
    geom_vline(xintercept = log(40), colour = "gray90", linetype = 2) +
    geom_line(aes(colour = obs), alpha = 0.8, ...) +
    scale_colour_manual(values = palette,
                        name = "Brain region",
                        labels = unname(brain_region_labels)) +
    ggtitle(fda_output$fdNames$gene) +
    guides(colour = guide_legend(ncol = ncol_legend)) +
    theme_min() +
    xlab("Age (PCW prenatally, years postnatally)") +
    ylab("Expression") +
    scale_x_continuous(breaks = log(fda_output$fdNames$age_pcw), labels = stringr::str_split(fda_output$fdNames$age, " ") %>% sapply(getElement, 1)) +
    # A hack to not show all axis labels...
    # https://stackoverflow.com/questions/31732597/how-to-not-show-all-labels-on-ggplot-axis#comment87387614_46409142
    theme(axis.text.x = element_text(size = rel(0.9), color = rep(c("black", rep("transparent", each = 5)), 7)),
          strip.background = element_blank()) +
    ylim(c(0, NA))
  
  return(p1)
  
}



plotFittedCurvesPerRegion <- function(fda_output, points = TRUE, ncol_legend = 2, limits = NULL, ...) {
  
  # The funData package has plotting methods for fda objects
  # using ggplot2
  require(funData)
  require(RColorBrewer)
  
  fdobj <- fda_output$lst_GE_FD[[1]]
  
  # We need to provide the values at which the fda curves will be approximated,
  # so I'll follow the defaults used in the fda package:
  # https://github.com/cran/fda/blob/master/R/plot.fd.R#L18
  basisobj <- fdobj$basis
  rangex   <- basisobj$rangeval
  nbasis   <- dim(fdobj$coefs)[1]
  nx       <- max(c(501,10*nbasis + 1))
  y        <- seq(rangex[1], rangex[2], len = round(nx))
  
  fundataobj <- fd2funData(fdobj, y)
  
  # Get points ----
  ge <- fda_output$lst_GE_IMP[[1]] %>% t()
  colnames(ge) <- fda_output$fdNames$region
  ge <- as.data.frame(ge) %>%
    mutate(age = log(fda_output$fdNames$age_pcw)) %>%
    gather(obs, expression, 1:16)
  
  ge_NA <- fda_output$lst_GE_wNA[[1]] %>% t()
  colnames(ge_NA) <- fda_output$fdNames$region
  ge_NA <- as.data.frame(ge_NA) %>%
    mutate(age = log(fda_output$fdNames$age_pcw)) %>%
    gather(obs, expression_NA, 1:16) %>%
    mutate(imputed = ifelse(is.na(expression_NA), "Imputed", "Observed"))
  
  ge_tidy <- suppressMessages(left_join(ge, ge_NA))
  
  # Plot w/ ggplot2 ----
  
  p1 <- autoplot(fundataobj) +
    geom_vline(xintercept = log(40), colour = "gray90", linetype = 2) +
    geom_line(alpha = 0.8, ...) +
    ggtitle(fda_output$fdNames$gene) +
    facet_wrap(~ obs, labeller = region_labeller) +
    theme_min() +
    xlab("Age (PCW prenatally, years postnatally)") +
    ylab("Expression") +
    scale_x_continuous(breaks = log(fda_output$fdNames$age_pcw), labels = stringr::str_split(fda_output$fdNames$age, " ") %>% sapply(getElement, 1)) +
    # A hack to not show all axis labels...
    # https://stackoverflow.com/questions/31732597/how-to-not-show-all-labels-on-ggplot-axis#comment87387614_46409142
    theme(axis.text.x = element_text(size = rel(0.9), color = rep(c("black", rep("transparent", each = 5)), 7)),
          strip.background = element_blank())
  
  if (points) p1 <- p1 +
    geom_point(data = ge_tidy,
               mapping = aes(x = age, y = expression, colour = imputed),
               alpha = 0.6,
               size = 1.5) +
    scale_colour_manual(values = c("Imputed" = "red", "Observed" = "gray40"))
  
  if (!is.null(limits)) p1 <- p1 + ylim(limits)
  
  return(p1)
  
}



theme_min <- function(base_size = 11, base_family = "",
                      border_colour = "grey90",
                      border_size = 1) {
  
  theme_light(base_size = 11, base_family = "") +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      panel.border = element_rect(fill = NA, colour = border_colour, size = border_size),
      axis.ticks = element_line(colour = border_colour),
      strip.background = element_rect(fill = NA, colour = NA),
      strip.text.x = element_text(colour = "black", size = rel(1.2)),
      strip.text.y = element_text(colour = "black", size = rel(1.2)),
      title = element_text(size = rel(0.9)),
      axis.text = element_text(colour = "black", size = rel(1.2)),
      axis.title = element_text(colour = "black", size = rel(1.5)),
      legend.title = element_text(colour = "black", size = rel(1.2)),
      legend.key.size = unit(0.9, "lines"),
      legend.text = element_text(size = rel(0.7), colour = "black"),
      legend.key = element_rect(colour = NA, fill = NA),
      legend.background = element_rect(colour = NA, fill = NA)
    )
}



